name: dio_plus
description: Extended version of original dio package.
version: 1.0.0
repository: https://github.com/amrmhassan/dio_plus

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
